const githubResponse = """

{
  "total_count": 10123,
  "incomplete_results": false,
  "items": [
    {
      "login": "mateus",
      "id": 2091116,
      "node_id": "MDQ6VXNlcjIwOTExMTY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/2091116?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateus",
      "html_url": "https://github.com/mateus",
      "followers_url": "https://api.github.com/users/mateus/followers",
      "following_url": "https://api.github.com/users/mateus/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateus/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateus/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateus/subscriptions",
      "organizations_url": "https://api.github.com/users/mateus/orgs",
      "repos_url": "https://api.github.com/users/mateus/repos",
      "events_url": "https://api.github.com/users/mateus/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateus/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateuschaves",
      "id": 34848657,
      "node_id": "MDQ6VXNlcjM0ODQ4NjU3",
      "avatar_url": "https://avatars2.githubusercontent.com/u/34848657?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateuschaves",
      "html_url": "https://github.com/mateuschaves",
      "followers_url": "https://api.github.com/users/mateuschaves/followers",
      "following_url": "https://api.github.com/users/mateuschaves/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateuschaves/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateuschaves/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateuschaves/subscriptions",
      "organizations_url": "https://api.github.com/users/mateuschaves/orgs",
      "repos_url": "https://api.github.com/users/mateuschaves/repos",
      "events_url": "https://api.github.com/users/mateuschaves/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateuschaves/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateusortiz",
      "id": 3077085,
      "node_id": "MDQ6VXNlcjMwNzcwODU=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/3077085?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateusortiz",
      "html_url": "https://github.com/mateusortiz",
      "followers_url": "https://api.github.com/users/mateusortiz/followers",
      "following_url": "https://api.github.com/users/mateusortiz/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateusortiz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateusortiz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateusortiz/subscriptions",
      "organizations_url": "https://api.github.com/users/mateusortiz/orgs",
      "repos_url": "https://api.github.com/users/mateusortiz/repos",
      "events_url": "https://api.github.com/users/mateusortiz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateusortiz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "seanlilmateus",
      "id": 625177,
      "node_id": "MDQ6VXNlcjYyNTE3Nw==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/625177?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/seanlilmateus",
      "html_url": "https://github.com/seanlilmateus",
      "followers_url": "https://api.github.com/users/seanlilmateus/followers",
      "following_url": "https://api.github.com/users/seanlilmateus/following{/other_user}",
      "gists_url": "https://api.github.com/users/seanlilmateus/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/seanlilmateus/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/seanlilmateus/subscriptions",
      "organizations_url": "https://api.github.com/users/seanlilmateus/orgs",
      "repos_url": "https://api.github.com/users/seanlilmateus/repos",
      "events_url": "https://api.github.com/users/seanlilmateus/events{/privacy}",
      "received_events_url": "https://api.github.com/users/seanlilmateus/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateusfreira",
      "id": 234049,
      "node_id": "MDQ6VXNlcjIzNDA0OQ==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/234049?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateusfreira",
      "html_url": "https://github.com/mateusfreira",
      "followers_url": "https://api.github.com/users/mateusfreira/followers",
      "following_url": "https://api.github.com/users/mateusfreira/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateusfreira/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateusfreira/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateusfreira/subscriptions",
      "organizations_url": "https://api.github.com/users/mateusfreira/orgs",
      "repos_url": "https://api.github.com/users/mateusfreira/repos",
      "events_url": "https://api.github.com/users/mateusfreira/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateusfreira/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MateuszKubuszok",
      "id": 1900121,
      "node_id": "MDQ6VXNlcjE5MDAxMjE=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1900121?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MateuszKubuszok",
      "html_url": "https://github.com/MateuszKubuszok",
      "followers_url": "https://api.github.com/users/MateuszKubuszok/followers",
      "following_url": "https://api.github.com/users/MateuszKubuszok/following{/other_user}",
      "gists_url": "https://api.github.com/users/MateuszKubuszok/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MateuszKubuszok/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MateuszKubuszok/subscriptions",
      "organizations_url": "https://api.github.com/users/MateuszKubuszok/orgs",
      "repos_url": "https://api.github.com/users/MateuszKubuszok/repos",
      "events_url": "https://api.github.com/users/MateuszKubuszok/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MateuszKubuszok/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mfpinheiro",
      "id": 8331550,
      "node_id": "MDQ6VXNlcjgzMzE1NTA=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/8331550?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mfpinheiro",
      "html_url": "https://github.com/mfpinheiro",
      "followers_url": "https://api.github.com/users/mfpinheiro/followers",
      "following_url": "https://api.github.com/users/mfpinheiro/following{/other_user}",
      "gists_url": "https://api.github.com/users/mfpinheiro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mfpinheiro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mfpinheiro/subscriptions",
      "organizations_url": "https://api.github.com/users/mfpinheiro/orgs",
      "repos_url": "https://api.github.com/users/mfpinheiro/repos",
      "events_url": "https://api.github.com/users/mfpinheiro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mfpinheiro/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MateusAndrade",
      "id": 15278828,
      "node_id": "MDQ6VXNlcjE1Mjc4ODI4",
      "avatar_url": "https://avatars1.githubusercontent.com/u/15278828?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MateusAndrade",
      "html_url": "https://github.com/MateusAndrade",
      "followers_url": "https://api.github.com/users/MateusAndrade/followers",
      "following_url": "https://api.github.com/users/MateusAndrade/following{/other_user}",
      "gists_url": "https://api.github.com/users/MateusAndrade/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MateusAndrade/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MateusAndrade/subscriptions",
      "organizations_url": "https://api.github.com/users/MateusAndrade/orgs",
      "repos_url": "https://api.github.com/users/MateusAndrade/repos",
      "events_url": "https://api.github.com/users/MateusAndrade/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MateusAndrade/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MateusAquino",
      "id": 16140783,
      "node_id": "MDQ6VXNlcjE2MTQwNzgz",
      "avatar_url": "https://avatars1.githubusercontent.com/u/16140783?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MateusAquino",
      "html_url": "https://github.com/MateusAquino",
      "followers_url": "https://api.github.com/users/MateusAquino/followers",
      "following_url": "https://api.github.com/users/MateusAquino/following{/other_user}",
      "gists_url": "https://api.github.com/users/MateusAquino/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MateusAquino/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MateusAquino/subscriptions",
      "organizations_url": "https://api.github.com/users/MateusAquino/orgs",
      "repos_url": "https://api.github.com/users/MateusAquino/repos",
      "events_url": "https://api.github.com/users/MateusAquino/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MateusAquino/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MateusGabi",
      "id": 14940643,
      "node_id": "MDQ6VXNlcjE0OTQwNjQz",
      "avatar_url": "https://avatars3.githubusercontent.com/u/14940643?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MateusGabi",
      "html_url": "https://github.com/MateusGabi",
      "followers_url": "https://api.github.com/users/MateusGabi/followers",
      "following_url": "https://api.github.com/users/MateusGabi/following{/other_user}",
      "gists_url": "https://api.github.com/users/MateusGabi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MateusGabi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MateusGabi/subscriptions",
      "organizations_url": "https://api.github.com/users/MateusGabi/orgs",
      "repos_url": "https://api.github.com/users/MateusGabi/repos",
      "events_url": "https://api.github.com/users/MateusGabi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MateusGabi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MateusZitelli",
      "id": 201472,
      "node_id": "MDQ6VXNlcjIwMTQ3Mg==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/201472?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MateusZitelli",
      "html_url": "https://github.com/MateusZitelli",
      "followers_url": "https://api.github.com/users/MateusZitelli/followers",
      "following_url": "https://api.github.com/users/MateusZitelli/following{/other_user}",
      "gists_url": "https://api.github.com/users/MateusZitelli/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MateusZitelli/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MateusZitelli/subscriptions",
      "organizations_url": "https://api.github.com/users/MateusZitelli/orgs",
      "repos_url": "https://api.github.com/users/MateusZitelli/repos",
      "events_url": "https://api.github.com/users/MateusZitelli/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MateusZitelli/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateusmuller",
      "id": 13832410,
      "node_id": "MDQ6VXNlcjEzODMyNDEw",
      "avatar_url": "https://avatars0.githubusercontent.com/u/13832410?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateusmuller",
      "html_url": "https://github.com/mateusmuller",
      "followers_url": "https://api.github.com/users/mateusmuller/followers",
      "following_url": "https://api.github.com/users/mateusmuller/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateusmuller/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateusmuller/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateusmuller/subscriptions",
      "organizations_url": "https://api.github.com/users/mateusmuller/orgs",
      "repos_url": "https://api.github.com/users/mateusmuller/repos",
      "events_url": "https://api.github.com/users/mateusmuller/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateusmuller/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateusjatenee",
      "id": 10816999,
      "node_id": "MDQ6VXNlcjEwODE2OTk5",
      "avatar_url": "https://avatars1.githubusercontent.com/u/10816999?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateusjatenee",
      "html_url": "https://github.com/mateusjatenee",
      "followers_url": "https://api.github.com/users/mateusjatenee/followers",
      "following_url": "https://api.github.com/users/mateusjatenee/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateusjatenee/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateusjatenee/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateusjatenee/subscriptions",
      "organizations_url": "https://api.github.com/users/mateusjatenee/orgs",
      "repos_url": "https://api.github.com/users/mateusjatenee/repos",
      "events_url": "https://api.github.com/users/mateusjatenee/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateusjatenee/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateusfg7",
      "id": 40613276,
      "node_id": "MDQ6VXNlcjQwNjEzMjc2",
      "avatar_url": "https://avatars1.githubusercontent.com/u/40613276?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateusfg7",
      "html_url": "https://github.com/mateusfg7",
      "followers_url": "https://api.github.com/users/mateusfg7/followers",
      "following_url": "https://api.github.com/users/mateusfg7/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateusfg7/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateusfg7/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateusfg7/subscriptions",
      "organizations_url": "https://api.github.com/users/mateusfg7/orgs",
      "repos_url": "https://api.github.com/users/mateusfg7/repos",
      "events_url": "https://api.github.com/users/mateusfg7/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateusfg7/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateusKoppe",
      "id": 12251731,
      "node_id": "MDQ6VXNlcjEyMjUxNzMx",
      "avatar_url": "https://avatars2.githubusercontent.com/u/12251731?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateusKoppe",
      "html_url": "https://github.com/mateusKoppe",
      "followers_url": "https://api.github.com/users/mateusKoppe/followers",
      "following_url": "https://api.github.com/users/mateusKoppe/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateusKoppe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateusKoppe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateusKoppe/subscriptions",
      "organizations_url": "https://api.github.com/users/mateusKoppe/orgs",
      "repos_url": "https://api.github.com/users/mateusKoppe/repos",
      "events_url": "https://api.github.com/users/mateusKoppe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateusKoppe/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateuszbuda",
      "id": 5720638,
      "node_id": "MDQ6VXNlcjU3MjA2Mzg=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/5720638?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateuszbuda",
      "html_url": "https://github.com/mateuszbuda",
      "followers_url": "https://api.github.com/users/mateuszbuda/followers",
      "following_url": "https://api.github.com/users/mateuszbuda/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateuszbuda/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateuszbuda/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateuszbuda/subscriptions",
      "organizations_url": "https://api.github.com/users/mateuszbuda/orgs",
      "repos_url": "https://api.github.com/users/mateuszbuda/repos",
      "events_url": "https://api.github.com/users/mateuszbuda/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateuszbuda/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateusfmachado",
      "id": 20207447,
      "node_id": "MDQ6VXNlcjIwMjA3NDQ3",
      "avatar_url": "https://avatars2.githubusercontent.com/u/20207447?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateusfmachado",
      "html_url": "https://github.com/mateusfmachado",
      "followers_url": "https://api.github.com/users/mateusfmachado/followers",
      "following_url": "https://api.github.com/users/mateusfmachado/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateusfmachado/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateusfmachado/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateusfmachado/subscriptions",
      "organizations_url": "https://api.github.com/users/mateusfmachado/orgs",
      "repos_url": "https://api.github.com/users/mateusfmachado/repos",
      "events_url": "https://api.github.com/users/mateusfmachado/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateusfmachado/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateusprado",
      "id": 111603,
      "node_id": "MDQ6VXNlcjExMTYwMw==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/111603?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateusprado",
      "html_url": "https://github.com/mateusprado",
      "followers_url": "https://api.github.com/users/mateusprado/followers",
      "following_url": "https://api.github.com/users/mateusprado/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateusprado/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateusprado/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateusprado/subscriptions",
      "organizations_url": "https://api.github.com/users/mateusprado/orgs",
      "repos_url": "https://api.github.com/users/mateusprado/repos",
      "events_url": "https://api.github.com/users/mateusprado/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateusprado/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateuspontes",
      "id": 342161,
      "node_id": "MDQ6VXNlcjM0MjE2MQ==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/342161?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateuspontes",
      "html_url": "https://github.com/mateuspontes",
      "followers_url": "https://api.github.com/users/mateuspontes/followers",
      "following_url": "https://api.github.com/users/mateuspontes/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateuspontes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateuspontes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateuspontes/subscriptions",
      "organizations_url": "https://api.github.com/users/mateuspontes/orgs",
      "repos_url": "https://api.github.com/users/mateuspontes/repos",
      "events_url": "https://api.github.com/users/mateuspontes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateuspontes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mpgxc",
      "id": 13613590,
      "node_id": "MDQ6VXNlcjEzNjEzNTkw",
      "avatar_url": "https://avatars2.githubusercontent.com/u/13613590?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mpgxc",
      "html_url": "https://github.com/mpgxc",
      "followers_url": "https://api.github.com/users/mpgxc/followers",
      "following_url": "https://api.github.com/users/mpgxc/following{/other_user}",
      "gists_url": "https://api.github.com/users/mpgxc/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mpgxc/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mpgxc/subscriptions",
      "organizations_url": "https://api.github.com/users/mpgxc/orgs",
      "repos_url": "https://api.github.com/users/mpgxc/repos",
      "events_url": "https://api.github.com/users/mpgxc/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mpgxc/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateuszmalinowski",
      "id": 274613,
      "node_id": "MDQ6VXNlcjI3NDYxMw==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/274613?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateuszmalinowski",
      "html_url": "https://github.com/mateuszmalinowski",
      "followers_url": "https://api.github.com/users/mateuszmalinowski/followers",
      "following_url": "https://api.github.com/users/mateuszmalinowski/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateuszmalinowski/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateuszmalinowski/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateuszmalinowski/subscriptions",
      "organizations_url": "https://api.github.com/users/mateuszmalinowski/orgs",
      "repos_url": "https://api.github.com/users/mateuszmalinowski/repos",
      "events_url": "https://api.github.com/users/mateuszmalinowski/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateuszmalinowski/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "maateusx",
      "id": 9124945,
      "node_id": "MDQ6VXNlcjkxMjQ5NDU=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/9124945?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/maateusx",
      "html_url": "https://github.com/maateusx",
      "followers_url": "https://api.github.com/users/maateusx/followers",
      "following_url": "https://api.github.com/users/maateusx/following{/other_user}",
      "gists_url": "https://api.github.com/users/maateusx/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/maateusx/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/maateusx/subscriptions",
      "organizations_url": "https://api.github.com/users/maateusx/orgs",
      "repos_url": "https://api.github.com/users/maateusx/repos",
      "events_url": "https://api.github.com/users/maateusx/events{/privacy}",
      "received_events_url": "https://api.github.com/users/maateusx/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateusz",
      "id": 118653,
      "node_id": "MDQ6VXNlcjExODY1Mw==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/118653?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateusz",
      "html_url": "https://github.com/mateusz",
      "followers_url": "https://api.github.com/users/mateusz/followers",
      "following_url": "https://api.github.com/users/mateusz/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateusz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateusz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateusz/subscriptions",
      "organizations_url": "https://api.github.com/users/mateusz/orgs",
      "repos_url": "https://api.github.com/users/mateusz/repos",
      "events_url": "https://api.github.com/users/mateusz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateusz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateusjunges",
      "id": 19756164,
      "node_id": "MDQ6VXNlcjE5NzU2MTY0",
      "avatar_url": "https://avatars2.githubusercontent.com/u/19756164?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateusjunges",
      "html_url": "https://github.com/mateusjunges",
      "followers_url": "https://api.github.com/users/mateusjunges/followers",
      "following_url": "https://api.github.com/users/mateusjunges/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateusjunges/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateusjunges/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateusjunges/subscriptions",
      "organizations_url": "https://api.github.com/users/mateusjunges/orgs",
      "repos_url": "https://api.github.com/users/mateusjunges/repos",
      "events_url": "https://api.github.com/users/mateusjunges/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateusjunges/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateuszdyminski",
      "id": 4962812,
      "node_id": "MDQ6VXNlcjQ5NjI4MTI=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/4962812?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateuszdyminski",
      "html_url": "https://github.com/mateuszdyminski",
      "followers_url": "https://api.github.com/users/mateuszdyminski/followers",
      "following_url": "https://api.github.com/users/mateuszdyminski/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateuszdyminski/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateuszdyminski/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateuszdyminski/subscriptions",
      "organizations_url": "https://api.github.com/users/mateuszdyminski/orgs",
      "repos_url": "https://api.github.com/users/mateuszdyminski/repos",
      "events_url": "https://api.github.com/users/mateuszdyminski/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateuszdyminski/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateusbzerra",
      "id": 17644982,
      "node_id": "MDQ6VXNlcjE3NjQ0OTgy",
      "avatar_url": "https://avatars3.githubusercontent.com/u/17644982?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateusbzerra",
      "html_url": "https://github.com/mateusbzerra",
      "followers_url": "https://api.github.com/users/mateusbzerra/followers",
      "following_url": "https://api.github.com/users/mateusbzerra/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateusbzerra/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateusbzerra/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateusbzerra/subscriptions",
      "organizations_url": "https://api.github.com/users/mateusbzerra/orgs",
      "repos_url": "https://api.github.com/users/mateusbzerra/repos",
      "events_url": "https://api.github.com/users/mateusbzerra/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateusbzerra/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateusduboli",
      "id": 1688249,
      "node_id": "MDQ6VXNlcjE2ODgyNDk=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1688249?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateusduboli",
      "html_url": "https://github.com/mateusduboli",
      "followers_url": "https://api.github.com/users/mateusduboli/followers",
      "following_url": "https://api.github.com/users/mateusduboli/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateusduboli/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateusduboli/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateusduboli/subscriptions",
      "organizations_url": "https://api.github.com/users/mateusduboli/orgs",
      "repos_url": "https://api.github.com/users/mateusduboli/repos",
      "events_url": "https://api.github.com/users/mateusduboli/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateusduboli/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateuszzwierzycki",
      "id": 2178452,
      "node_id": "MDQ6VXNlcjIxNzg0NTI=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/2178452?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateuszzwierzycki",
      "html_url": "https://github.com/mateuszzwierzycki",
      "followers_url": "https://api.github.com/users/mateuszzwierzycki/followers",
      "following_url": "https://api.github.com/users/mateuszzwierzycki/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateuszzwierzycki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateuszzwierzycki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateuszzwierzycki/subscriptions",
      "organizations_url": "https://api.github.com/users/mateuszzwierzycki/orgs",
      "repos_url": "https://api.github.com/users/mateuszzwierzycki/repos",
      "events_url": "https://api.github.com/users/mateuszzwierzycki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateuszzwierzycki/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateuszmackowiak",
      "id": 1284783,
      "node_id": "MDQ6VXNlcjEyODQ3ODM=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1284783?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateuszmackowiak",
      "html_url": "https://github.com/mateuszmackowiak",
      "followers_url": "https://api.github.com/users/mateuszmackowiak/followers",
      "following_url": "https://api.github.com/users/mateuszmackowiak/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateuszmackowiak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateuszmackowiak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateuszmackowiak/subscriptions",
      "organizations_url": "https://api.github.com/users/mateuszmackowiak/orgs",
      "repos_url": "https://api.github.com/users/mateuszmackowiak/repos",
      "events_url": "https://api.github.com/users/mateuszmackowiak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateuszmackowiak/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mateusmirandaalmeida",
      "id": 13368319,
      "node_id": "MDQ6VXNlcjEzMzY4MzE5",
      "avatar_url": "https://avatars3.githubusercontent.com/u/13368319?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mateusmirandaalmeida",
      "html_url": "https://github.com/mateusmirandaalmeida",
      "followers_url": "https://api.github.com/users/mateusmirandaalmeida/followers",
      "following_url": "https://api.github.com/users/mateusmirandaalmeida/following{/other_user}",
      "gists_url": "https://api.github.com/users/mateusmirandaalmeida/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mateusmirandaalmeida/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mateusmirandaalmeida/subscriptions",
      "organizations_url": "https://api.github.com/users/mateusmirandaalmeida/orgs",
      "repos_url": "https://api.github.com/users/mateusmirandaalmeida/repos",
      "events_url": "https://api.github.com/users/mateusmirandaalmeida/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mateusmirandaalmeida/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}

""";